const testItems = [
  {
    name: "The Latest Drop",
    highestBid: "2.5",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Newest Drop",
    highestBid: "5",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Coolest Drop",
    highestBid: "7",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Oldest Drop",
    highestBid: "1.5",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Latest Drop",
    highestBid: "2.5",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Newest Drop",
    highestBid: "5",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Coolest Drop",
    highestBid: "7",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Oldest Drop",
    highestBid: "1.5",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Latest Drop",
    highestBid: "2.5",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Newest Drop",
    highestBid: "5",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Coolest Drop",
    highestBid: "7",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Oldest Drop",
    highestBid: "1.5",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Latest Drop",
    highestBid: "2.5",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Newest Drop",
    highestBid: "5",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Coolest Drop",
    highestBid: "7",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Oldest Drop",
    highestBid: "1.5",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Latest Drop",
    highestBid: "2.5",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Newest Drop",
    highestBid: "5",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Coolest Drop",
    highestBid: "7",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Oldest Drop",
    highestBid: "1.5",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Latest Drop",
    highestBid: "2.5",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Newest Drop",
    highestBid: "5",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Coolest Drop",
    highestBid: "7",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Oldest Drop",
    highestBid: "1.5",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Latest Drop",
    highestBid: "2.5",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Newest Drop",
    highestBid: "5",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Coolest Drop",
    highestBid: "7",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Oldest Drop",
    highestBid: "1.5",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Latest Drop",
    highestBid: "2.5",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Newest Drop",
    highestBid: "5",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Coolest Drop",
    highestBid: "7",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Oldest Drop",
    highestBid: "1.5",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Latest Drop",
    highestBid: "2.5",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Newest Drop",
    highestBid: "5",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Coolest Drop",
    highestBid: "7",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Oldest Drop",
    highestBid: "1.5",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Latest Drop",
    highestBid: "2.5",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Newest Drop",
    highestBid: "5",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Coolest Drop",
    highestBid: "7",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Oldest Drop",
    highestBid: "1.5",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Latest Drop",
    highestBid: "2.5",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Newest Drop",
    highestBid: "5",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Coolest Drop",
    highestBid: "7",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Oldest Drop",
    highestBid: "1.5",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Latest Drop",
    highestBid: "2.5",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Newest Drop",
    highestBid: "5",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Coolest Drop",
    highestBid: "7",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Oldest Drop",
    highestBid: "1.5",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
];

export default testItems;
