const testItems = [
  {
    id: "id",
    name: "The Latest Drop",
    highestBid: "2.5",
    image: "url(/images/mclaren.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    id: "id",
    name: "The Latest Drop",
    highestBid: "2.5",
    image: "url(/images/mclaren.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    id: "id",
    name: "The Latest Drop",
    highestBid: "2.5",
    image: "url(/images/mclaren.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    id: "id",
    name: "The Latest Drop",
    highestBid: "2.5",
    image: "url(/images/mclaren.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    id: "id",
    name: "The Latest Drop",
    highestBid: "2.5",
    image: "url(/images/mclaren.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    id: "id",
    name: "The Latest Drop",
    highestBid: "2.5",
    image: "url(/images/mclaren.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    id: "id",
    name: "The Latest Drop",
    highestBid: "2.5",
    image: "url(/images/mclaren.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    id: "id",
    name: "The Latest Drop",
    highestBid: "2.5",
    image: "url(/images/mclaren.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    id: "id",
    name: "The Latest Drop",
    highestBid: "2.5",
    image: "url(/images/mclaren.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    id: "id",
    name: "The Latest Drop",
    highestBid: "2.5",
    image: "url(/images/mclaren.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    id: "id",
    name: "The Latest Drop",
    highestBid: "2.5",
    image: "url(/images/mclaren.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
];

export default testItems;
