export const config = [
  {
    name: "Leopard Mesh x Fox Fur (Runway)",
    creator: "@iamjenniferle",
    collection: "Long Story Short",
    price: "2.50",
    total: 5,
    sold: 2,
    startTime: new Date(),
  },
];

export const description = [
  {
    description:
      "IAMJENNIFERLE  “Runway” Collection gives me full range to play & execute concepts that double as wearable ART✨ \n Lorem ipsum dolor sit amet, consectetur adipiscing elit. Habitant a ornare lacus viverra eleifend sapien ac tellus aliquam. Enim odio nunc nulla diam sed quam amet, elementum metus. Non gravida ut mi, ultrices nunc elit nisl odio. Facilisis fermentum diam viverra elementum pretium, volutpat, orci feugiat. Erat nisi, dictum dignissim odio eros cras urna cras. Facilisis massa diam sed mauris. Nisl morbi dolor sit in euismod hendrerit mattis.",
    nftDetails:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc at tortor at orci ullamcorper lacinia ac vitae turpis. Aliquam at dui eget lorem tempus dignissim. Sed commodo purus eu fringilla vulputate. Aenean lacinia eu enim quis vestibulum. In eu ligula ullamcorper turpis feugiat condimentum id ac nunc. Suspendisse tortor mi, scelerisque ac vehicula a, pharetra et libero. Integer blandit purus rhoncus tortor finibus, ut scelerisque nisl ultricies. Sed mi quam, semper ac blandit sit amet, venenatis vel ex. Nam dictum libero in sem accumsan accumsan. Vivamus sit amet gravida neque. Donec eu molestie lectus.",
    productDetails:
      "In quis ex auctor, efficitur sapien id, varius sapien. Sed ut tellus ac ex efficitur scelerisque vitae ac justo. Proin finibus, eros ac tincidunt semper, urna augue faucibus neque, a lacinia nisi est quis ex. Ut convallis, nunc non rhoncus imperdiet, urna sapien fermentum ex, gravida volutpat turpis diam quis nibh. Curabitur molestie odio cursus sem venenatis, id elementum enim luctus. Etiam mi nisl, fermentum a malesuada non, congue quis enim. Integer rhoncus vitae nisi id sollicitudin. Ut hendrerit magna quis dolor sodales commodo. Proin sit amet suscipit tellus. Phasellus porta felis ac ultricies dictum. Sed vehicula malesuada mollis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur finibus, nisl sed luctus euismod, justo lorem elementum elit, non tempor risus tortor in turpis. In eu quam sodales, suscipit nisl ut, blandit nunc. Curabitur eu velit egestas, euismod enim vel, bibendum leo.",
  },
];

export const chartTitle = ["Minted", "Price", "From", "To", "Date"];

export const chartContent = [
  ["Sale", "2.34", "Oncyber", "kkt", "2 months ago"],
  ["Transfer", "", "IamNeo", "BoredPoorGuy", "2 months ago"],
  ["Transfer", "5.23", "Robotbot", "BoredPoorGuy", "2 months ago"],
  ["Sale", "2.34", "Oncyber", "kkt", "2 months ago"],
];

export const testItems = [
  {
    name: "The Latest Drop",
    highestBid: "2.5",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Newest Drop",
    highestBid: "5",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Coolest Drop",
    highestBid: "7",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Oldest Drop",
    highestBid: "1.5",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Latest Drop",
    highestBid: "2.5",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Newest Drop",
    highestBid: "5",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Coolest Drop",
    highestBid: "7",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Oldest Drop",
    highestBid: "1.5",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Latest Drop",
    highestBid: "2.5",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Newest Drop",
    highestBid: "5",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Coolest Drop",
    highestBid: "7",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Oldest Drop",
    highestBid: "1.5",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Latest Drop",
    highestBid: "2.5",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Newest Drop",
    highestBid: "5",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Coolest Drop",
    highestBid: "7",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Oldest Drop",
    highestBid: "1.5",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Latest Drop",
    highestBid: "2.5",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Newest Drop",
    highestBid: "5",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Coolest Drop",
    highestBid: "7",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Oldest Drop",
    highestBid: "1.5",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Latest Drop",
    highestBid: "2.5",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Newest Drop",
    highestBid: "5",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Coolest Drop",
    highestBid: "7",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Oldest Drop",
    highestBid: "1.5",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Latest Drop",
    highestBid: "2.5",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Newest Drop",
    highestBid: "5",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Coolest Drop",
    highestBid: "7",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Oldest Drop",
    highestBid: "1.5",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Latest Drop",
    highestBid: "2.5",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Newest Drop",
    highestBid: "5",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Coolest Drop",
    highestBid: "7",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Oldest Drop",
    highestBid: "1.5",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Latest Drop",
    highestBid: "2.5",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Newest Drop",
    highestBid: "5",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Coolest Drop",
    highestBid: "7",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Oldest Drop",
    highestBid: "1.5",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Latest Drop",
    highestBid: "2.5",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Newest Drop",
    highestBid: "5",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Coolest Drop",
    highestBid: "7",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Oldest Drop",
    highestBid: "1.5",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Latest Drop",
    highestBid: "2.5",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Newest Drop",
    highestBid: "5",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Coolest Drop",
    highestBid: "7",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Oldest Drop",
    highestBid: "1.5",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Latest Drop",
    highestBid: "2.5",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Newest Drop",
    highestBid: "5",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Coolest Drop",
    highestBid: "7",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
  {
    name: "The Oldest Drop",
    highestBid: "1.5",
    image: "url(/images/shopImage.svg)",
    startTime: new Date(),
    mintTime: new Date(),
  },
];
